version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  build-tools: circleci/build-tools@2.6.3
referenced:
  defaults: &defaults
    docker:
      - image: circleci/python:3.8.2-buster
  dependencies: &dependencies
    run:
      name: Dependencies
      command: |
        sudo apt-get install -y rsync clang-format cppcheck clang-tidy libperlio-gzip-perl libjson-perl
        sudo python -m pip install --upgrade pip
        sudo python -m pip install lxml scikit-ci-addons
        sudo ci_addons circle/install_cmake.py 3.17.1
      working_directory: '~/'
workflows:
  build-and-test:
    jobs: 
      - compile
      - test:
          requires:
            - compile
      - check_format:
          requires:
            - compile
      - check_tidy:
          requires:
            - compile
      - check_cppcheck:
          requires:
            - compile
jobs:
  compile:
    <<: *defaults
    steps:
      - *dependencies
      - checkout
      - run:
          name: Update Git Submodules
          command: |
            git submodule sync
            git submodule update --init
      - run:
          name: Creating Build Files
          command: 'cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DDEVOPT_ENABLE_COVERAGE_REPORT=On'
      - run:
          name: Building All
          command: 'cmake --build build -j 2'
      - persist_to_workspace:
          root: ./
          paths: ./
  test:
    <<: *defaults
    steps:
      - *dependencies
      - attach_workspace:
          at: ./
      - run:
          name: Running Tests
          command: ctest -j 2 -T Test --output-on-failure
          working_directory: build
      - run:
          name: Running LCOV
          command: bash .ci/lcov.bash build
      - codecov/upload:
          file: build/coverage.info
      - run:
          name: Converting Test Output
          command: |
            mkdir -p /tmp/test-results/CTest
            ci_addons ctest_junit_formatter build > /tmp/test-results/CTest/results.xml
      - store_test_results:
          path: /tmp/test-results
  check_format:
    <<: *defaults
    steps:
      - *dependencies
      - attach_workspace:
          at: ./      
      - run:
          name: Checking Source Code Format
          command: 'cmake --build build --target check_format -j 2'
      - store_artifacts:
          path: build/check_format_mcberepair.xml
  check_tidy:
    <<: *defaults
    steps:
      - *dependencies
      - attach_workspace:
          at: ./      
      - run:
          name: Checking Source with ClangTidy
          command: 'cmake --build build --target check_tidy -j 2'
      - store_artifacts:
          path: build/check_tidy_mcberepair.txt
  check_cppcheck:
    <<: *defaults
    steps:
      - *dependencies
      - attach_workspace:
          at: ./
      - run:
          name: Checking Source with Cppcheck
          command: 'cmake --build build --target check_cppcheck -j 2'
      - store_artifacts:
          path: build/cppcheck_results.xml
